# name: Earthquake Data

# on:
#   schedule:
#     - cron: '*/30 * * * *'  # Menjalankan setiap 30 menit
#   push:
#     branches:
#       - main

# jobs:
#   update_data:
#     runs-on: ubuntu-latest

#     steps:
#     - name: Checkout repository
#       uses: actions/checkout@v3

#     - name: Set up Python
#       uses: actions/setup-python@v3
#       with:
#         python-version: '3.9'

#     - name: Install dependencies
#       run: |
#         pip install pandas requests gspread oauth2client matplotlib cartopy Pillow instagrapi

#     - name: Run main script
#       run: python main.py
#       env:
#         CREDENTIALS_API: ${{ secrets.CREDENTIALS_API }}
